Softstarter: Src/main.c File Reference
main.c File Reference
: Programa para o controle do softstarter e da comunicacao com a interface
#include "main.h"
#include "stm32f4xx_hal.h"
#include "cmsis_os.h"
#include <math.h>
Macros
#define ADC_RES_Vrms 0.16748
Resolucao do ADC do Vrms.
#define Vpike 342
Definicao do Vpico de Vrms.
#define Aquisitions 26
Numero de aquisicoes durante a subida e descida para o grafico.
#define Increment_minimum 1
Valor minimo do angulo (varia de 1-100)
#define Arr_period 102
#define Vrms_ERROR 1.3
Erro compensado na medida Vrms.
#define Irms_ERROR 1
Erro compensado na medida Irms.
Enumerations
enum calls {
START = 0x72, STOP = 0x66, EMERGENCY = 0x61, VRMSREAD = 0x76,
IRMSREAD = 0x69, CURRENTSET = 0x63
}
enum dos comandos recebidos pela interface
Functions
void SystemClock_Config (void)
System Clock Configuration.
void Measure_Thread (void const *argument)
Thread para o calculo rms das medidas dos ADC's.
void Serial_Thread (void const *argument)
Thread que controla o envio e o recebimento da serial.
void RPM_Thread (void const *argument)
void Alarm_Thread (void const *argument)
Thread que checa Irms>150%, Irms>200% e desenergizacao do motor.
void Initialization_Thread (void const *argument)
Thread executada sempre que o programa e inicializado.
void SoftStart_Thread (void const *argument)
Thread responsavel por atualizar o puslo de controle e monitora-lo.
void Chart_Thread (void const *argument)
Thread responsavel por fazer a aquisicao dos graficos de subida e descida.
void HAL_TIM_MspPostInit (TIM_HandleTypeDef *htim)
void Emergency (void)
Funcao que executa todas medidas necessarias para emergencia.
int main (void)
The application entry point.
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *hadc)
Callback executado sempre que o DMA termina todas conversoes dos ADC´s.
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non blocking mode.
void _Error_Handler (char *file, int line)
This function is executed in case of error occurrence.
Variables
ADC_HandleTypeDef hadc1
ADC1 usado para medidas de tensao.
ADC_HandleTypeDef hadc2
ADC2 usado para medidas de corrente.
DMA_HandleTypeDef hdma_adc1
ADC1 usado com DMA.
DMA_HandleTypeDef hdma_adc2
ADC2 usado com DMA.
TIM_HandleTypeDef htim1
Timer 1 usado para atualizar o deslocamento do pulso de controle.
TIM_HandleTypeDef htim2
Timer 2 usado para triggar a conversao dos ADC's por DMA.
TIM_HandleTypeDef htim3
Timer 3 usado para gerar o pulso de controle (PWM)
TIM_HandleTypeDef htim4
Timer 4 usado para contar RPM (IC)
UART_HandleTypeDef huart2
Comunicacao por cabo.
UART_HandleTypeDef huart6
Comunicacao por bluetooth.
osThreadId Measure_TaskHandle
osThreadId Serial_TaskHandle
osThreadId RPM_TaskHandle
osThreadId Alarm_TaskHandle
osThreadId Initialization_Handle
osThreadId SoftStart_TaskHandle
osThreadId Chart_TaskHandle
xSemaphoreHandle ADC_Conv_Semaphore = 0
Semaforo para sincronizacao do AD com a thread de calculo rms.
xSemaphoreHandle Increment_Semaphore = 0
Semaforo para sincronizacao do deslocamento de pulso com a thread de atualizacao do pulso.
xSemaphoreHandle Emergency_Semaphore = 0
Semaforo para envio de notificacao de emergencia a interface.
xSemaphoreHandle E150_Semaphore = 0
Semaforo para envio de notificacao de corrente > 150% a interface.
uint16_t ADC_Values_Vrms [16]
Vetor que recebe conversao do ADC1.
uint16_t ADC_Values_Irms [16]
Vetor que recebe conversao do ADC2.
uint16_t Nominal_Current = 500
Variavel que recebe corrente nominal do motor da interface.
uint16_t Ipike = 1000
Variavel que recebe o Ipico da medida Irms.
uint16_t Irms_data_rise [Aquisitions]
Vetor das medidas Irms do grafico de subida.
uint16_t Irms_data_fall [Aquisitions]
Vetor das medidas Irms do grafico de descida.
uint16_t i200 = 10000
Variavel que armazena valor de 200% de Irms.
uint16_t i150 = 10000
Variavel que armazena valor de 150% de Irms.
uint16_t Vrms
Variavel que recebe valor final de Vrms.
uint16_t Irms
Variavel que recebe valor final de Irms.
uint8_t rising_time = 5
Variavel que recebe tempo de subida.
uint8_t falling_time = 5
Variavel que recebe tempo de descida.
uint8_t increment = 102
Variavel que desloca os pulsos de controle.
uint8_t rise = 0
Flag que indica se o motor esta acelerando.
uint8_t fall = 0
Flag que indica se o motor esta desacelerando.
uint8_t Pulse_Width = 2
Definicao da largura do pulso de controle.
uint8_t rise_ok = 0
Flag que indica o fim da aceleracao.
uint8_t fall_ok = 0
Flag que indica o fim da desaceleracao.
uint8_t check = 1
Flag que indica atualizacao da posicao do pulso de controle.
uint8_t Nominal_Current_SET = 0
Flag que indica se a corrente nominal foi definida na interface.
float ADC_RES_Irms = 0.48828
Variavel que recebe a resolucao do ADC de Irms.
Detailed Description
: Programa para o controle do softstarter e da comunicacao com a interface
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners.
Copyright (c) 2018 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file main.c.
Enumeration Type Documentation
calls
enum calls
enum dos comandos recebidos pela interface
Note
START:Comando recebido para iniciar
STOP:Comando recebido para parar
EMERGENCY:Comando recebido para parada de emergencia
VRMSREAD:Comando exigindo medida Vrms como retorno
IRMSREAD:Comando exigindo medida Irms como retorno
CURRENTSET:Comando que define a corrente nominal do motor
Definition at line 79 of file main.c.
Function Documentation
_Error_Handler()
void _Error_Handler (char * file, int line)
This function is executed in case of error occurrence.
Parameters
file The file name as string.
line The line in file as a number.
Return values
None
Definition at line 1283 of file main.c.
Referenced by SystemClock_Config().
Alarm_Thread()
void Alarm_Thread (void const * argument)
Thread que checa Irms>150%, Irms>200% e desenergizacao do motor.
Note
Caso Irms>150% o pulso retorna 3 unidades (1-100)
Caso Irms>200% e acionado a emergencia
Caso haja desenergizacao do motor e acionado a emergencia
Checa se Irms>150% durante a aceleracao
Checa se Irms>200%
Checa se o motor foi desenergizado durante a aceleracao ou enquanto estava em funcionamento
Definition at line 1090 of file main.c.
References E150_Semaphore, Emergency(), Emergency_Semaphore, i150, i200, increment, Irms, rise, and Vrms.
Chart_Thread()
void Chart_Thread (void const * argument)
Thread responsavel por fazer a aquisicao dos graficos de subida e descida.
Note
Checa se o motor esta acelerando ou desacelerando e preenche o respectivo vetor do grafico
Realiza 25 medidas durante a transicao ('increment % 4', onde 'increment' varia de 1-100)
Realiza a medida 26 ao final de cada transicao
Variavel de contagem das aquisicoes
Definition at line 1206 of file main.c.
References Aquisitions, check, fall, increment, Irms, Irms_data_fall, Irms_data_rise, and rise.
Emergency()
void Emergency (void)
Funcao que executa todas medidas necessarias para emergencia.
Note
Zera as flags que indicam aceleracao ou desaceleracao
Desliga os dois reles, o de alimentacao e o de bypass
Para o timer responsavel por gerar o pulso de controle
Seta a variavel 'increment' para seu valor inicial
Definition at line 214 of file main.c.
References fall, htim3, increment, and rise.
Referenced by Alarm_Thread().
HAL_ADC_ConvCpltCallback()
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef * hadc)
Callback executado sempre que o DMA termina todas conversoes dos ADC´s.
Note
Disponibiliza o semaforo 'ADC_Conv_Semaphore', permitindo o calculo rms das conversoes
Definition at line 786 of file main.c.
References ADC_Conv_Semaphore.
HAL_TIM_MspPostInit()
void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)
TIM3 GPIO Configuration PA6 ---—> TIM3_CH1
Definition at line 306 of file stm32f4xx_hal_msp.c.
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non blocking mode.
Note
This function is called when TIM14 interrupt took place, inside HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment a global variable "uwTick" used as application time base.
Parameters
htim : TIM handle
Return values
None
Checa se a interrupcao foi feita por TIM1
Disponibiliza o semaforo 'Increment_Semaphore' e seta a flag 'check' indicando atualizacao de 'increment'
Checa se o motor esta acelerando e se Irms<150% para deslocar o pulso
Checa se o motor esta desacelerando para deslocar o pulso
Definition at line 1253 of file main.c.
References Increment_Semaphore.
Initialization_Thread()
void Initialization_Thread (void const * argument)
Thread executada sempre que o programa e inicializado.
Note
Possui prioridade RealTime e e suspendida apos executada uma vez
Inicializa os perifericos a serem utilizados e cria os semaforos
Definition at line 1123 of file main.c.
References ADC_Conv_Semaphore, ADC_Values_Irms, ADC_Values_Vrms, E150_Semaphore, Emergency_Semaphore, hadc1, hadc2, htim2, and Increment_Semaphore.
main()
int main (void)
The application entry point.
Return values
None
Definition at line 233 of file main.c.
References SystemClock_Config().
Measure_Thread()
void Measure_Thread (void const * argument)
Thread para o calculo rms das medidas dos ADC's.
Note
Somente e executada se o semaforo 'ADC_Conv_Semaphore' esta disponivel
Para a medida Vrms e setado um offset em 2048, portando -Vpico = 0V e +Vpico = 3v3
Para a medida Irms e utilizado um retificador de precisao, nao sendo necessario o offset
Nos dois casos e realizado a media dos 16 valores convertidos, que e multiplicado pela resolucao correspondente do seu ADC, esse valor e elevado ao quadrado
Esse processo e realizado 16 vezes, e entao e realizada outra media do valor quadratico
Por fim e feita a raiz quadrada dessa media quadratica, retornando o valor final rms
Vetor que recebe os valores convertidos de tensao de cada ciclo
Vetor que recebe os valores convertidos de corrente de cada ciclo
Variavel de contagem de ciclos
So realiza o calculo de Irms caso a corrente nominal tenha sido definida
So realiza o calculo de Irms caso a corrente nominal tenha sido definida
Definition at line 803 of file main.c.
References ADC_Conv_Semaphore, ADC_RES_Irms, ADC_RES_Vrms, ADC_Values_Irms, ADC_Values_Vrms, Irms, Irms_ERROR, Nominal_Current_SET, Vpike, Vrms, and Vrms_ERROR.
Serial_Thread()
void Serial_Thread (void const * argument)
Thread que controla o envio e o recebimento da serial.
Note
Possui um caso para cada chamada da interface
Verifica as flags e semaforos que indicam a necessidade de envio de confirmacao a interface
Caracter que indica a ordem da interface
Vetor que contem o tempo de subida ou descida definido na interface
Variavel que recebe o tamanho da string a ser enviada
String para envio de dados solicitados a interface
Stirng para envio de mensagens a interface
Procedimentos realizados quando a corrente nominal e definida na interface
Sinaliza erro na definicao da corrente nominal para interface
Retorna a medida Vrms para a interface
Retorna a medida Irms para a interface
Procedimentos realizados quando e ordenado a aceleracao
Retorna o sucesso da comunicacao a interface
Indica que o comando nao foi realizado com sucesso
Indica para a interface que o motor esta em transicao
Indica para interface que o motor ja esta ligado
Procedimentos realizados quando e ordenado a desaceleracao
Retorna o sucesso da comunicacao a interface
Indica que o comando nao foi realizado com sucesso
Indica para a interface que o motor esta em transicao
Indica para interface que o motor ja esta desligado
Procedimentos realizados quando e ordenado a parada de emergencia
Indica o fim da aceleracao a interface e envia os valores para o grafico de subida
Indica o fim da desaceleracao a interface e envia os valores para o grafico de descida
Indica uma emergencia a interface
Indica Irms > 150% a interface
Definition at line 902 of file main.c.
References huart6.
SoftStart_Thread()
void SoftStart_Thread (void const * argument)
Thread responsavel por atualizar o puslo de controle e monitora-lo.
Note
Realiza o deslocamento do puslo de controle
Indica com flags quando o motor foi acelerado ou desacelerado
A Thread so e executada quando ha atualizacao na variavel 'increment'
Seta o inicio do pulso para 'increment' e seu final para 'increment' + 'Pulse_Width'
Procedimentos realizados quando o motor e desacelerado
Seta o inicio do pulso para 'increment' e seu final para 'increment' + 'Pulse_Width'
Procedimentos realizados quando o motor e acelerado
Definition at line 1147 of file main.c.
References fall, htim3, increment, Increment_Semaphore, and Pulse_Width.
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the CPU, AHB and APB busses clocks
Initializes the CPU, AHB and APB busses clocks
Configure the Systick interrupt time
Configure the Systick
Definition at line 342 of file main.c.
References _Error_Handler().
Referenced by main().
Variable Documentation
hdma_adc1
DMA_HandleTypeDef hdma_adc1
ADC1 usado com DMA.
File Name : stm32f4xx_hal_msp.c Description : This file provides code for the MSP Initialization and de-Initialization codes.
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners.
Copyright (c) 2018 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 96 of file main.c.
Referenced by DMA2_Stream0_IRQHandler().